services:
  app:
    volumes:
      - geoip_data:/var/www/html/var/geoip:ro
      - uploads_data:/var/www/html/public/uploads
    depends_on:
      geoip-updater:
        condition: service_completed_successfully
      database:
        condition: service_started
    env_file:
      - .env.prod
    restart: unless-stopped

  assets:
    image: ghcr.io/boxsubmus/spinda-app:latest
    entrypoint: ["sh", "-c", "rm -rf /shared/* && cp -r /var/www/html/public/. /shared/ && rm -rf /shared/uploads && mkdir -p /shared/uploads"]
    volumes:
      - app_public:/shared
    restart: "no"

  webserver:
    ports:
      - "80:80"
    volumes:
      - app_public:/var/www/html/public:ro
      - uploads_data:/var/www/html/public/uploads:ro
    depends_on:
      assets:
        condition: service_completed_successfully
      app:
        condition: service_started

  database:
    env_file:
      - .env.prod
    restart: unless-stopped

  scheduler:
    image: ghcr.io/boxsubmus/spinda-app:latest
    command: php bin/console messenger:consume scheduler_default -vv
    volumes:
      - geoip_data:/var/www/html/var/geoip:ro
    depends_on:
      - app
      - database
    env_file:
      - .env.prod
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - database
    restart: unless-stopped

volumes:
  app_public:
  uploads_data: