services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    image: spinda-app-dev
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: dev
    user: "1000:1000"
    ports:
      - "5173:5173"

  webserver:
    ports:
      - "1337:80"
    volumes:
      - ./src:/var/www/html

  database:
    environment:
      MARIADB_DATABASE: spinda
      MARIADB_USER: app
      MARIADB_PASSWORD: app
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - "8081:80"
    depends_on:
      - database

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    command: php bin/console messenger:consume scheduler_default -vv
    depends_on:
      - app
      - database
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html